# Generated by Django 6.0.6 on 2026-07-09 16:29

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Chat',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.TextField(verbose_name='내용')),
                ('sent_at', models.DateTimeField(auto_now_add=True, verbose_name='전송일시')),
            ],
            options={
                'verbose_name': '채팅',
                'db_table': 'chat',
                'ordering': ['sent_at'],
            },
        ),
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, verbose_name='프로젝트명')),
                ('progress', models.IntegerField(default=0, verbose_name='진행률')),
                ('status', models.CharField(choices=[('IN_PROGRESS', '진행중'), ('COMPLETED', '완료')], default='IN_PROGRESS', max_length=20, verbose_name='상태')),
                ('start_date', models.DateField(verbose_name='시작일')),
                ('end_date', models.DateField(verbose_name='종료일')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='생성일시')),
            ],
            options={
                'verbose_name': '프로젝트',
                'db_table': 'project',
            },
        ),
        migrations.CreateModel(
            name='ProjectFile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file_path', models.FileField(upload_to='project_files/', verbose_name='파일')),
                ('folder_name', models.CharField(blank=True, max_length=100, null=True, verbose_name='폴더명')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True, verbose_name='업로드일시')),
            ],
            options={
                'verbose_name': '프로젝트파일',
                'db_table': 'project_file',
            },
        ),
        migrations.CreateModel(
            name='ProjectMember',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(blank=True, max_length=50, null=True, verbose_name='역할')),
            ],
            options={
                'verbose_name': '프로젝트멤버',
                'db_table': 'project_member',
            },
        ),
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, verbose_name='제목')),
                ('deadline', models.DateField(blank=True, null=True, verbose_name='마감일')),
                ('status', models.CharField(choices=[('TODO', '할일'), ('DOING', '진행중'), ('DONE', '완료')], default='TODO', max_length=10, verbose_name='상태')),
            ],
            options={
                'verbose_name': '할일',
                'db_table': 'task',
            },
        ),
    ]
