# Generated by Django 6.0.7 on 2026-07-09 14:42

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Proposal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, verbose_name='제목')),
                ('goal', models.TextField(verbose_name='목표')),
                ('message', models.TextField(blank=True, null=True, verbose_name='메시지')),
                ('mode', models.CharField(choices=[('ONE', '1:1 교환형'), ('GROUP', '소그룹')], max_length=10, verbose_name='협업모드')),
                ('period', models.IntegerField(verbose_name='기간(주)')),
                ('weekly_time', models.CharField(choices=[('ONE_TO_FOUR', '1~4시간'), ('FIVE_TO_TEN', '5~10시간'), ('ELEVEN_TO_TWENTY', '11~20시간'), ('OVER_TWENTY', '20시간 이상')], max_length=20, verbose_name='주당시간')),
                ('communication', models.CharField(choices=[('KAKAO', '카카오톡'), ('GOOGLE_MEET', '구글 미트'), ('DISCORD', '디스코드'), ('ETC', '기타')], max_length=20, verbose_name='소통수단')),
                ('attachment', models.FileField(blank=True, null=True, upload_to='proposals/', verbose_name='첨부파일')),
                ('status', models.CharField(choices=[('WAIT', '대기'), ('ACCEPT', '수락'), ('REJECT', '거절')], default='WAIT', max_length=10, verbose_name='상태')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='생성일시')),
            ],
            options={
                'verbose_name': '제안',
                'db_table': 'proposal',
            },
        ),
    ]
