# Generated by Django 6.0.6 on 2026-07-09 16:29

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('match', '0001_initial'),
        ('user', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='proposal',
            name='give_talent',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='give_proposals', to='user.talent', verbose_name='기부재능'),
        ),
        migrations.AddField(
            model_name='proposal',
            name='need_talent',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='need_proposals', to='user.talent', verbose_name='희망재능'),
        ),
        migrations.AddField(
            model_name='proposal',
            name='receiver',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='received_proposals', to=settings.AUTH_USER_MODEL, verbose_name='수신자'),
        ),
        migrations.AddField(
            model_name='proposal',
            name='sender',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sent_proposals', to=settings.AUTH_USER_MODEL, verbose_name='발신자'),
        ),
    ]
